o_adjectives = [
    "Vast",
    "Salty",
    "Deep",
    "Turbulent",
    "Calm",
    "Azure",
    "Endless",
    "Majestic",
    "Mysterious",
    "Serene",
    "Raging",
    "Tempestuous",
    "Crystal",
    "Blue",
    "Teeming",
    "Shimmering",
    "Boundless",
    "Tranquil",
    "Roaring",
    "Choppy",
    "Murky",
    "Foamy",
    "Glistening",
    "Sapphire",
    "Dark",
    "Luminous",
    "Sprawling",
    "Fathomless",
    "Rippling",
    "Cool",
    "Tumultuous",
    "Breezy",
    "Briny",
    "Sundrenched",
    "Moonlit",
    "Sparkling",
    "Vibrant",
    "Ominous",
    "Thundering",
    "Aquamarine",
    "Pristine",
    "Swirling",
    "Whispering",
    "Crashing",
    "Dazzling",
    "Timeless",
    "Infinite",
    "Expansive",
    "Undulating",
    "Reflective",
    "Gentle",
    "Wild",
    "Restless",
    "Clear",
    "Seething",
    "Tide-kissed",
    "Wavy",
    "Glassy",
    "Jeweled",
    "Sunlit",
    "Shadowy",
    "Muted",
    "Tropical",
    "Frigid",
    "Silvery",
    "Misty",
    "Stormy",
    "Placid",
    "Eerie",
    "Ethereal",
    "Sultry",
    "Bubbling",
    "Sweeping",
    "Frothy",
    "Lush",
    "Pacific",
    "Languid",
    "Nautical",
    "Twinkling",
    "Haunting",
    "Emerald",
    "Windy",
    "Hushed",
    "Billowing",
    "Cerulean",
    "Golden",
    "Deep-sea",
    "Marine",
    "Sunkissed",
    "Turbid",
    "Enigmatic",
    "Coastal",
    "Pearlescent",
    "Hypnotic"
]

p_adjectives = [
    "Vast",
    "Rolling",
    "Endless",
    "Golden",
    "Grassy",
    "Open",
    "Sweeping",
    "Flat",
    "Expansive",
    "Barren",
    "Fertile",
    "Lush",
    "Prairie",
    "Stark",
    "Boundless",
    "Serene",
    "Rustling",
    "Windswept",
    "Verdant",
    "Sparse",
    "Distant",
    "Majestic",
    "Untamed",
    "Wild",
    "Tranquil",
    "Sunlit",
    "Shadowed",
    "Breezy",
    "Vibrant",
    "Pastoral",
    "Rippling",
    "Muted",
    "Dry",
    "Green",
    "Harsh",
    "Idyllic",
    "Limitless",
    "Meadowy",
    "Nurturing",
    "Ochre",
    "Parched",
    "Quiet",
    "Rural",
    "Scenic",
    "Tawny",
    "Unbroken",
    "Vivid",
    "Waving",
    "Xeric",
    "Yielding",
    "Zephyrous",
    "Amber",
    "Bucolic",
    "Calm",
    "Dewy",
    "Ethereal",
    "Fallow",
    "Gentle",
    "Horizon-reaching",
    "Inviting",
    "Jade",
    "Kinetic",
    "Lonely",
    "Mesmeric",
    "Natural",
    "Oasis-like",
    "Picturesque",
    "Quiescent",
    "Restful",
    "Sylvan",
    "Tumultuous",
    "Unending",
    "Vast",
    "Whispering",
    "Exotic",
    "Yearning",
    "Zenithal",
    "Alive",
    "Blissful",
    "Cultivated",
    "Dappled",
    "Effulgent",
    "Flourishing",
    "Glowing",
    "Hallowed",
    "Illuminated",
    "Jubilant"
]

h_adjectives = [
     "Rolling",
    "Verdant",
    "Gentle",
    "Steep",
    "Majestic",
    "Undulating",
    "Lush",
    "Rugged",
    "Elevated",
    "Green",
    "Sloping",
    "Misty",
    "Distant",
    "Barren",
    "Fertile",
    "Bare",
    "Grassy",
    "Rocky",
    "Serene",
    "Towering",
    "Breezy",
    "Isolated",
    "Scenic",
    "Hazy",
    "Golden",
    "Silent",
    "Sunlit",
    "Shadowed",
    "Windswept",
    "Rippling",
    "Mossy",
    "Pastoral",
    "Terraced",
    "Tranquil",
    "Wild",
    "Jagged",
    "Picturesque",
    "Quaint",
    "Rising",
    "Stony",
    "Tumultuous",
    "Uplifting",
    "Vibrant",
    "Wavy",
    "Xerophilous",
    "Youthful",
    "Zigzagging",
    "Amber",
    "Bucolic",
    "Crested",
    "Dewy",
    "Eroded",
    "Fringed",
    "Glistening",
    "Hollowed",
    "Illuminated",
    "Jutting",
    "Knoll-like",
    "Lofty",
    "Mounded",
    "Nestled",
    "Outstretched",
    "Pleasant",
    "Quiescent",
    "Rustic",
    "Secluded",
    "Thicketed",
    "Undisturbed",
    "Veiled",
    "Wooded",
    "Exalted",
    "Yearning",
    "Zenithal",
    "Alive",
    "Bluff-like",
    "Craggy",
    "Dotted",
    "Enchanted",
    "Flourishing",
    "Grazed",
    "Heathered",
    "Inviting",
    "Jeweled"
]

m_adjectives = [
   "Majestic",
    "Snow-capped",
    "Rugged",
    "Lofty",
    "Soaring",
    "Steep",
    "Imposing",
    "Grand",
    "Elevated",
    "Rocky",
    "Pinnacle",
    "Mighty",
    "Towering",
    "Jagged",
    "Formidable",
    "Ancient",
    "Looming",
    "Stark",
    "Verdant",
    "Mystical",
    "Barren",
    "Isolated",
    "Volcanic",
    "Impressive",
    "Daunting",
    "Silent",
    "Serene",
    "Vast",
    "Dramatic",
    "Craggy",
    "Enchanted",
    "Foreboding",
    "Glistening",
    "Hallowed",
    "Icy",
    "Jovian",
    "Kingly",
    "Lustrous",
    "Monolithic",
    "Noble",
    "Ominous",
    "Pristine",
    "Quaint",
    "Resplendent",
    "Sacred",
    "Thrusting",
    "Unyielding",
    "Venerable",
    "Windswept",
    "Xenolithic",
    "Yielding",
    "Zenithal",
    "Alpine",
    "Breathtaking",
    "Colossal",
    "Dominant",
    "Ethereal",
    "Fabled",
    "Gargantuan",
    "Harsh",
    "Invincible",
    "Jubilant",
    "Kaleidoscopic",
    "Legendary",
    "Majestical",
    "Nurtured",
    "Overwhelming",
    "Picturesque",
    "Quixotic",
    "Revered",
    "Stalwart",
    "Timeless",
    "Unassailable",
    "Valiant",
    "Whispering",
    "Exalted",
    "Yonder",
    "Zealous",
    "Awed",
    "Boundless",
    "Celestial",
    "Distinguished",
    "Enduring",
    "Frosty",
    "Glorious",
    "Heavenly",
    "Immutable",
    "Jaw-dropping"
]

f_adjectives = [
   "Dense",
    "Lush",
    "Mystical",
    "Verdant",
    "Ancient",
    "Enchanted",
    "Thick",
    "Shaded",
    "Leafy",
    "Primeval",
    "Whispering",
    "Serene",
    "Untamed",
    "Wild",
    "Sylvan",
    "Secluded",
    "Bountiful",
    "Majestic",
    "Canopied",
    "Twilight",
    "Dappled",
    "Rustling",
    "Sacred",
    "Timeless",
    "Ethereal",
    "Shadowed",
    "Tranquil",
    "Vibrant",
    "Fragrant",
    "Mossy",
    "Ferny",
    "Gloomy",
    "Sun-dappled",
    "Towering",
    "Bucolic",
    "Calm",
    "Evergreen",
    "Deciduous",
    "Glistening",
    "Hallowed",
    "Iridescent",
    "Jungle-like",
    "Kaleidoscopic",
    "Labyrinthine",
    "Murmuring",
    "Nocturnal",
    "Overgrown",
    "Picturesque",
    "Quaint",
    "Resplendent",
    "Soothing",
    "Tangled",
    "Untouched",
    "Venerable",
    "Whimsical",
    "Xanadu-like",
    "Yearning",
    "Zen-like",
    "Alive",
    "Bird-filled",
    "Cathedral-like",
    "Dreamy",
    "Elysian",
    "Fairy-tale",
    "Gnarled",
    "Haunting",
    "Invigorating",
    "Jeweled",
    "Kinetic",
    "Luminescent",
    "Mystifying",
    "Nurturing",
    "Opulent",
    "Pristine",
    "Quixotic",
    "Revered",
    "Sacrosanct",
    "Teeming",
    "Uncharted",
    "Vivid",
    "Wondrous",
    "Exotic",
    "Yielding",
    "Zephyrous"
]
#######################
o_nouns = [
    "Abyss",
    "Atoll",
    "Basin",
    "Bight",
    "Billow",
    "Brine",
    "Canyon",
    "Channel",
    "Chasm",
    "Cove",
    "Current",
    "Deep",
    "Delta",
    "Eddy",
    "Estuary",
    "Fathom",
    "Fjord",
    "Gulf",
    "Horizon",
    "Inlet",
    "Islet",
    "Jetstream",
    "Lagoon",
    "Maelstrom",
    "Narrows",
    "Ocean",
    "Passage",
    "Reef",
    "Ridge",
    "Ripple",
    "Salinity",
    "Seabed",
    "Seafloor",
    "Seamount",
    "Shoal",
    "Sound",
    "Strait",
    "Surf",
    "Swell",
    "Tide",
    "Trench",
    "Trough",
    "Undertow",
    "Upwelling",
    "Vortex",
    "Wave",
    "Whirlpool",
    "Riptide",
    "Thermocline",
    "Vents"
]

p_nouns = [
   "Basin",
    "Bench",
    "Butte",
    "Chaparral",
    "Dale",
    "Depression",
    "Divide",
    "Dune",
    "Expanse",
    "Fallows",
    "Flatland",
    "Grassland",
    "Heath",
    "Highland",
    "Horizon",
    "Knoll",
    "Lowland",
    "Meadow",
    "Mesa",
    "Mire",
    "Moor",
    "Outwash",
    "Pampas",
    "Pasture",
    "Prairie",
    "Ravine",
    "Ridge",
    "Rise",
    "Savannah",
    "Scarp",
    "Steppe",
    "Tableland",
    "Tarn",
    "Terrace",
    "Tundra",
    "Upland",
    "Vale",
    "Valley",
    "Veld",
    "Vista",
    "Wash",
    "Wetland",
    "Wold",
    "Yield",
    "Zephyr",
    "Barrens",
    "Clearing",
    "Downs",
    "Escarpment"
]

h_nouns = [
    "Ascent",
    "Bank",
    "Bluff",
    "Brae",
    "Bump",
    "Butte",
    "Climb",
    "Crest",
    "Dale",
    "Decline",
    "Dell",
    "Down",
    "Drumlin",
    "Elevation",
    "Embankment",
    "Escarpment",
    "Expanse",
    "Fell",
    "Gradient",
    "Heath",
    "Highland",
    "Incline",
    "Knoll",
    "Ledge",
    "Mesa",
    "Mound",
    "Outcrop",
    "Peak",
    "Pinnacle",
    "Plateau",
    "Ravine",
    "Ridge",
    "Rise",
    "Slope",
    "Spur",
    "Summit",
    "Terrace",
    "Tor",
    "Upland",
    "Vale",
    "Valley",
    "Vista",
    "Wold",
    "Yawn",
    "Zigzag",
    "Bank",
    "Crag",
    "Declivity",
    "Eminence",
    "Foot"
]

m_nouns = [
        "Alp",
    "Apex",
    "Arete",
    "Ascent",
    "Base",
    "Bluff",
    "Boulder",
    "Canyon",
    "Cirque",
    "Cliff",
    "Col",
    "Crag",
    "Crest",
    "Divide",
    "Escarpment",
    "Foothill",
    "Gorge",
    "Highland",
    "Hillside",
    "Incline",
    "Knoll",
    "Ledge",
    "Massif",
    "Notch",
    "Outcrop",
    "Peak",
    "Pinnacle",
    "Plateau",
    "Range",
    "Ravine",
    "Ridge",
    "Scarp",
    "Slope",
    "Spire",
    "Summit",
    "Terrace",
    "Tor",
    "Trench",
    "Upland",
    "Valley",
    "Vista",
    "Volcano",
    "Watershed",
    "Yawn",
    "Zigzag",
    "Blade",
    "Cleft",
    "Dell",
    "Elevation"
]

f_nouns = [
    "Arbor",
    "Bosk",
    "Canopy",
    "Dell",
    "Expanse",
    "Fernery",
    "Glen",
    "Hollow",
    "Interval",
    "Jungle",
    "Knick",
    "Lair",
    "Meadow",
    "Nook",
    "Orchard",
    "Paddock",
    "Quagmire",
    "Ravine",
    "Stand",
    "Thicket",
    "Underbrush",
    "Vale",
    "Woodland",
    "Xyloflora",
    "Yield",
    "Zone",
    "Brush",
    "Clearing",
    "Dense",
    "Edge",
    "Floor",
    "Grove",
    "Habitat",
    "Interior",
    "Jade",
    "Knot",
    "Layer",
    "Moss",
    "Nest",
    "Overgrowth",
    "Patch",
    "Quiet",
    "Root",
    "Shade",
    "Trail",
    "Understory",
    "Vista",
    "Wilderness",
    "Expanse"
]

t_name = [
     "Seabreeze Harbor",
    "Coral Cove",
    "Pirate's Cove",
    "Mermaid's Lagoon",
    "Skull Island",
    "Siren's Song",
    "Shipwreck Bay",
    "Treasure Isle",
    "Turtle Beach",
    "Moonlit Bay",
    "Sunset Shores",
    "Whalebone Village",
    "Azure Cove",
    "Mystic Isle",
    "Jungle Landing",
    "Pearl Harbor",
    "Windward Port",
    "Golden Sands",
    "Emerald Cove",
    "Dragonstone Port",
    "Kraken's Keep",
    "Blackbeard Bay",
    "Tidal Haven",
    "Sapphire Isle",
    "Stormy Harbor",
    "Rustic Wharf",
    "Whispering Pines",
    "Moonlit Haven",
    "Silvermoon Bay",
    "Hidden Anchorage",
     "Starfish Cove",
    "Misty Harbor",
    "Crimson Bay",
    "Dolphin's Cove",
    "Emerald Harbor",
    "Tropical Breeze",
    "Marine Village",
    "Cursed Cove",
    "Rainbow Shores",
    "Turtle Island",
    "Pirate's Paradise",
    "Witch's Haven",
    "Crystal Waters",
    "Coral Harbor",
    "Rusty Anchor",
    "Moonlit Oasis",
    "Ghostly Port",
    "Lighthouse Landing",
    "Fisherman's Retreat",
    "Dragon's Den",
    "Sapphire Harbor",
    "Jewel Bay",
    "Golden Sands Cove",
    "Treasure Cove",
    "Seashell Haven",
    "Abyssal Abyss",
    "Mystic Cove",
    "Mango Bay",
    "Silvershore",
    "Stormy Waters",
    "Merfolk's Refuge",
    "Wavesong Harbor",
    "Maritime Village",
    "Sunset Bay",
    "Amber Cove",
    "Kraken's Lair",
    "Tidepool Haven",
    "Whispering Pines Cove",
    "Cursed Island",
    "Blackwater Harbor",
    "Whale Song Bay",
    "Dragon's Breath Port",
    "Pirate's Retreat",
    "Pearl Cove",
    "Coral Reef Port",
    "Moonlit Lagoon",
    "Azure Harbor",
    "Rogue's Retreat",
    "Rainbow Harbor",
    "Hidden Treasure Bay",
    "Siren's Cove",
    "Volcano Bay",
    "Skeleton Island",
    "Crimson Harbor",
    "Witch's Cove",
    "Emerald Oasis",
    "Haunted Harbor",
    "Misty Shores",
    "Crystal Cove",
    "Mystical Waters",
    "Tidal Village",
    "Galleon's Graveyard",
    "Silverstrand Bay",
    "Palm Paradise",
    "Lighthouse Cove",
    "Dragon's Roar Port",
    "Sapphire Shores",
    "Mystic Sands",
    "Jewel Harbor",
    "Golden Anchor Bay",
    "Treasure Hunter's Haven",
    "Seashell Cove",
    "Abyssal Port",
    "Starfish Haven",
    "Sunken Ship Bay",
    "Cursed Treasure Cove",
    "Mermaid's Harbor",
    "Wavesong Village",
    "Coral Beach",
    "Siren's Retreat",
    "Black Pearl Cove",
    "Whale's Tail Bay",
    "Dragon's Claw Port",
    "Turtle Shell Cove",
    "Moonlit Cove",
    "Marine Haven",
    "Ghost Ship Bay",
    "Silvermoon Harbor",
    "Stormy Shore",
    "Turtle Haven",
    "Crystal Cove Village",
    "Mystic Bay",
    "Pirate's Rest",
    "Pearl Harbor Cove",
    "Sunset Oasis",
    "Treasure Trove Bay",
    "Emerald Sound",
    "Crimson Shores",
    "Dolphin Cove",
    "Sapphire Shores Cove",
    "Rusty Cutlass Cove",
    "Pirate's Plunder",
    "Misty Mirage",
    "Crimson Cove",
    "Aqua Bay",
    "Emerald Enclave",
    "Tropical Treasure",
    "Marina Vista",
    "Witch's Wharf",
    "Rainbow Retreat",
    "Atlantis Haven",
    "Dragon's Lair",
    "Sapphire Serenity",
    "Mermaid's Hideaway",
    "Jewel Junction",
    "Golden Galleon",
    "Treasure Trove",
    "Seaweed Sanctuary",
    "Abyssal Abyss",
    "Mystic Mirage",
    "Mango Mist",
    "Silver Serenity",
    "Stormy Secrets",
    "Merfolk's Marina",
    "Whispering Waters",
    "Marine Mysteries",
    "Sunset Serenade",
    "Amber Anchorage",
    "Kraken's Abyss",
    "Tidepool Tavern",
    "Coral Dreams",
    "Rusty Shipyard",
    "Moonlit Magic",
    "Ghost Ship Harbor",
    "Lighthouse Lookout",
    "Fisherman's Fortune",
    "Dragon's Dominion",
    "Sapphire Serenade",
    "Jewel Junction",
    "Golden Grotto",
    "Treasure Trail",
    "Seashell Shores",
    "Abyssal Adventure",
    "Mystic Magic",
    "Mango Mirage",
    "Silvershore Sanctuary",
    "Stormy Splendor",
    "Mermaid's Melody",
    "Wavesong Wharf",
    "Maritime Marvel",
    "Sunset Serenity",
    "Amber Azure",
    "Kraken's Keep",
    "Tidepool Treasure",
    "Coral Cove",
    "Rainbow Reflections",
    "Hidden Harbor",
    "Siren's Serenade",
    "Volcano Vista",
    "Skeleton's Cove",
    "Crimson Cape",
    "Witch's Wonders",
    "Emerald Echoes",
    "Haunted Hideaway",
    "Misty Mysteries",
    "Crystal Cascades",
    "Mystical Mirage",
    "Tidal Treasures",
    "Galleon's Gold",
    "Silverstrand Serenity",
    "Palm Paradise Cove",
    "Lighthouse Lookout",
    "Dragon's Domain",
    "Sapphire Splendor",
    "Mystic Meadows",
    "Jewel Junction Cove",
    "Golden Galleon Bay",
    "Treasure Hunter's Hideaway",
    "Seashell Serenity",
    "Abyssal Atoll",
    "Starfish Sanctuary",
    "Sunken Secrets",
    "Cursed Caverns",
    "Mermaid's Melody",
    "Wavesong Wonders",
    "Coral Cove",
    "Siren's Sanctuary",
    "Black Pearl Bay",
    "Whale's Watch",
    "Dragon's Dominion Cove",
    "Turtle's Treasure",
    "Moonlit Mysteries",
    "Marine Marvel",
    "Ghost Ship Grotto",
    "Silvermoon Serenade",
    "Stormy Splendors",
    "Turtle's Tranquility",
    "Crystal Cove",
    "Mystic Magic Cove",
    "Pirate's Paradise Cove",
    "Pearl Harbor Cove",
    "Sunset Serenity Cove",
    "Treasure Trove Cove",
    "Emerald Echoes Cove",
    "Crimson Cove",
    "Dolphin's Delight Cove",
    "Sapphire Splendor Cove",
    "Rusty Relic Cove",
    "Pirate's Perch",
    "Mystic Mirage Cove",
    "Crimson Shores Cove",
    "Aqua Haven",
    "Emerald Shores Cove",
    "Tropical Tranquility",
    "Marina Vista Cove",
    "Witch's Wharf Cove",
    "Rainbow Reef Cove",
    "Atlantis Oasis",
    "Dragon's Roost",
    "Sapphire Serenity Cove",
    "Mermaid's Cove",
    "Jewel Junction Cove",
    "Golden Grotto Cove",
    "Treasure Cove",
    "Seashell Cove",
    "Abyssal Abyss Cove",
    "Mystic Mirage Cove",
    "Mango Mist Cove",
    "Silver Serenity Cove",
    "Stormy Secrets Cove",
    "Merfolk's Marina Cove",
    "Whispering Waters Cove",
    "Marine Mysteries Cove",
    "Sunset Serenade Cove",
    "Amber Anchorage Cove",
    "Kraken's Abyss Cove",
    "Tidepool Tavern Cove",
    "Coral Dreams Cove",
    "Rusty Shipyard Cove",
    "Moonlit Magic Cove",
    "Ghost Ship Harbor Cove",
    "Lighthouse Lookout Cove",
    "Fisherman's Fortune Cove",
    "Dragon's Roost Cove",
    "Sapphire Serenade Cove",
    "Jewel Junction Cove",
    "Golden Grotto Cove",
    "Treasure Trail Cove",
    "Seashell Shores Cove",
    "Abyssal Adventure Cove",
    "Mystic Magic Cove",
    "Mango Mirage Cove",
    "Silvershore Sanctuary Cove",
    "Stormy Splendor Cove",
    "Mermaid's Melody Cove",
    "Wavesong Wharf Cove",
    "Maritime Marvel Cove",
    "Sunset Serenity Cove",
    "Amber Azure Cove",
    "Kraken's Keep Cove",
    "Tidepool Treasure Cove",
    "Coral Cove",
    "Rainbow Reflections Cove",
    "Hidden Harbor Cove",
    "Siren's Serenade Cove",
    "Volcano Vista Cove",
    "Skeleton's Cove",
    "Crimson Cape Cove",
    "Witch's Wonders Cove",
    "Emerald Echoes Cove",
    "Haunted Hideaway Cove",
    "Misty Mysteries Cove",
    "Crystal Cascades Cove",
    "Mystical Mirage Cove",
    "Tidal Treasures Cove",
    "Galleon's Gold Cove",
    "Silverstrand Serenity Cove",
        "Portsmouth",
    "Harborview",
    "Seaview",
    "Anchor's End",
    "Marinatown",
    "Bayshore",
    "Cresthaven",
    "Lakewood",
    "Fairharbor",
    "Windsor Cove",
    "Stonebridge",
    "Brookside",
    "Kingsport",
    "Newport",
    "Havenfield",
    "Oceanville",
    "Rivertown",
    "Greenwich",
    "Cliffside",
    "Fishingham",
    "Millville",
    "Riverside",
    "Harbor Springs",
    "Highland Bay",
    "Covebridge",
    "Piermont",
    "Hollyville",
    "Shoreside",
    "Maplewood",
    "Harborside",
    "Lighthouse Bay",
    "Rockport",
    "Beachwood",
    "Bayside",
    "Tidewater",
    "Sailor's Cove",
    "Summerfield",
    "Bridgewater",
    "Harborview Cove",
    "Meadowville",
    "Waverly",
    "Fisher's Cove",
    "Havenbrook",
    "Crestwood",
    "Rivershore",
    "Windward Bay",
    "Pinecrest",
    "Newbridge",
    "Seawinds",
    "Bayside Heights",
    "Seabrook",
    "Greenfield",
    "Portside",
    "Lakemont",
    "Marinaville",
    "Harborside Cove",
    "Tidewatch",
    "Shorehaven",
    "Fairwind",
    "Bayfield",
    "Oakridge",
    "Waterside",
    "Riverbend",
    "Sailor's Point",
    "Havenridge",
    "Brookside Cove",
    "Anchor's Landing",
    "Lighthouse Cove",
    "Woodbridge",
    "Riverside Cove",
    "Harborview Heights",
    "Harborside Village",
    "Highland Cove",
    "Crestwood Bay",
    "Bayside Park",
    "Cliffside Cove",
    "Seaside",
    "Seaview Cove",
    "Kingsbridge",
    "Piercove",
    "Lakemeadow",
    "Ocean Bay",
    "Harbor's Edge",
    "Fisher's Landing",
    "Bayside Point",
    "Bayhill",
    "Maplebridge",
    "Port Haven",
    "Waterside Village",
    "Lighthouse Point",
    "Sailor's Haven",
    "Bridgewater Cove",
    "Greenbriar",
    "Seaglen",
    "Marina Bay",
    "Tidewatch Cove",
    "Harbor Heights",
    "Riverbend Cove",
    "Bayside Terrace",
    "Crestwood Village",
    "Harbor's View",
    "Bayview Cove",
    "Brookside Village",
    "Shoreline",
    "Portside Cove",
    "Riverview",
    "Bayside Harbor",
    "Marinavista",
    "Bayfront",
    "Harbor Bayou",
    "Cliffview Cove",
    "Seahaven",
    "Harborwalk",
    "Bridgetown",
    "Lakeside",
    "Oceanwood",
    "Waveridge",
    "Seawind Cove",
    "Crestbrook",
    "Pier Harbor",
    "Harbor Village",
    "Coastal Cove",
    "Woodside",
    "Harbor Isle",
    "Bayside Cove",
    "Baycrest",
    "Marinaville Cove",
    "Beachside",
    "Bridgewood",
    "Tideview",
    "Anchor's Cove",
    "Harborfield",
    "Bayshire",
    "Harborview Village",
    "Seascape Cove",
    "Harbor Cove",
    "Portside Bay",
    "Riverside Village",
    "Bayshore Cove",
    "Marinatown Cove",
    "Cliffview Bay",
        "Seaspray",
    "Piermont Village",
    "Bayview Landing",
    "Havenbridge Cove",
    "Crestwood Harbor",
    "Maritime Point",
    "Beachfront Bay",
    "Harborwatch Cove",
    "Shoreside Village",
    "Seagrove",
    "Seabridge",
    "Anchor's Landing",
    "Fairview Cove",
    "Marinavista Bay",
    "Bayfield Terrace",
    "Lighthouse Pointe",
    "Ocean Crest",
    "Bridgewater Bay",
    "Rivertown Haven",
    "Harborside Bayou",
    "Harbor's Reach",
    "Woodside Haven",
    "Bayside Cove Heights",
    "Harborwalk Village",
    "Harborfield Heights",
    "Portside Bay Park",
    "Riverside Haven Cove",
    "Bayshore Coveview",
    "Marinatown Pointe",
    "Cliffview Bayport",
    "Harborside Vista",
    "Seahaven Shore",
    "Harborwalk Landing",
    "Bridgetown Shoreline",
    "Lakeside Bayview",
    "Oceanwood Bayfront",
    "Waveridge Port",
    "Seawind Harbor Village",
    "Crestbrook Harbor",
    "Pier Harbor Point",
    "Harbor Village Crossing",
    "Coastal Cove Beach",
    "Woodside Bayfront",
    "Harbor Isle Point",
    "Bayside Heights Crossing",
    "Baycrest Bayview",
    "Marinaville Pier",
    "Beachside Baywalk",
    "Bridgewood Shore",
    "Tideview Pointe",
    "Anchor's Reach",
    "Harborfield Baywood",
    "Bayshire Harbor",
    "Harborview Village Point",
    "Seascape Port",
    "Harbor Reach",
    "Portside Bay Harbor",
    "Riverside Village Crossing",
    "Bayshore Harborview",
    "Marinatown Point Landing",
    "Cliffview Bay Landing",
    "Harborside Bay Point",
    "Seahaven Shoreline",
    "Harborwalk Landing Point",
    "Bridgetown Shoreline Crossing",
    "Lakeside Bayview Point",
    "Oceanwood Bayfront Village",
    "Waveridge Port Crossing",
    "Seawind Harbor Village Point",
    "Crestbrook Harbor Point",
    "Pier Harbor Point Landing",
    "Harbor Village Crossing Point",
    "Coastal Cove Beach Landing",
    "Woodside Bayfront Landing",
    "Harbor Isle Point Village",
    "Bayside Heights Crossing Point",
    "Baycrest Bayview Point",
    "Marinaville Pier Village",
    "Beachside Baywalk Landing",
    "Bridgewood Shore Point",
    "Tideview Pointe Landing",
    "Anchor's Reach Village",
    "Harborfield Baywood Landing",
    "Bayshire Harbor Village",
    "Harborview Village Point Landing",
    "Seascape Port Village",
    "Harbor Reach Point",
    "Portside Bay Harbor Landing",
    "Riverside Village Crossing Point",
    "Bayshore Harborview Village",
    "Marinatown Point Landing Village",
    "Cliffview Bay Landing Village",
    "Harborside Bay Point Village",
    "Seahaven Shoreline Village",
    "Harborshade",
    "Misthaven",
    "Seawatch",
    "Tideholm",
    "Lunarport",
    "Sapphire Bay",
    "Stormreach",
    "Anchor's Rest",
    "Coral Cove",
    "Dawnharbor",
    "Wavewalker's Landing",
    "Mermaid's Lagoon",
    "Starshore",
    "Gull's Roost",
    "Nautical Nook",
    "Sirensong Harbor",
    "Pearlport",
    "Mariner's Mire",
    "Sunset Shores",
    "Whalewatch",
    "Saltwind",
    "Triton's Trench",
    "Seaglimmer",
    "Moonlit Marina",
    "Azure Anchorage",
    "Golden Gulf",
    "Shipwreck Cove",
    "Lighthouse Landing",
    "Ocean's Embrace",
    "Sailor's Solace",
    "Kraken's Kove",
    "Pelican Pier",
    "Mystic Mooring",
    "Seastone",
    "Wavecrest",
    "Marblequay",
    "Tidal Town",
    "Nereid's Nook",
    "Seashell Shore",
    "Buccaneer's Bay",
    "Dolphindale",
    "Maelstrom Marina",
    "Sail's End",
    "Cerulean City",
    "Galeharbor",
    "Thalassic Thoroughfare",
    "Pirate's Perch",
    "Neptune's Nest",
    "Voyager's Veil",
    "Horizon Hold",
       "Tempest's Touch",
    "Starfish Strand",
    "Mariner's Muse",
    "Crimson Cove",
    "Sable Sands",
    "Ebbtide Edge",
    "Jewel Jetty",
    "Fathom's Fall",
    "Sundown Seaport",
    "Lantern's Lure",
    "Oyster Oasis",
    "Windward Wharf",
    "Serpent's Slip",
    "Anchor's Awe",
    "Raven's Reef",
    "Duskhaven Dock",
    "Emerald Estuary",
    "Voyage Vale",
    "Sailshade",
    "Meridian Marina",
    "Orca's Outpost",
    "Lorelei Landing",
    "Beryl Bay",
    "Glimmergate Gulf",
    "Squall's Sanctuary",
    "Manta's Mire",
    "Twilight Tides",
    "Harpoon Harbor",
    "Nimbus Nook",
    "Sable Shore",
    "Pebbleport",
    "Lagoon's Lull",
    "Seadrift",
    "Mystmarina",
    "Turtle's Turn",
    "Sapphire Shoal",
    "Gale's Grasp",
    "Breezebound Bay",
    "Coral's Cradle",
    "Dewdrop Dock",
    "Finfolk's Folly",
    "Lunar Lagoon",
    "Siren's Sigh",
    "Masthaven",
    "Vesper's Veil",
    "Whisperwind Wharf",
    "Triton's Triumph",
    "Seafarer's Sanctuary",
    "Ripple Reach",
    "Nautical Nexus",
    "Abyssal Anchorage",
    "Balefire Bay",
    "Cobalt Cove",
    "Dawn's Descent",
    "Eagle's Estuary",
    "Frostfire Fjord",
    "Gull's Grotto",
    "Haven's Halt",
    "Ivory Isle",
    "Jade Jetty",
    "Kelp's Keep",
    "Lanternlight Landing",
    "Mystic Mews",
    "Narwhal Nook",
    "Opal Oasis",
    "Peregrine Port",
    "Quill Quay",
    "Rune's Refuge",
    "Starboard Strand",
    "Tidal Terrace",
    "Umbra Upland",
    "Voyager's Vista",
    "Windwhisper Warf",
    "Xanadu Xylem",
    "Yarncliff Yawl",
    "Zenith's Zen",
    "Aurora Anchorage",
    "Blaze's Bay",
    "Celestial Cove",
    "Dragon's Dock",
    "Eldritch Estuary",
    "Falcon's Fjord",
    "Ghostlight Gulf",
    "Horizon's Hearth",
    "Island's Insight",
    "Jubilee Jetty",
    "Kestrel's Keep",
    "Lunarlight Landing",
    "Maelstrom Mews",
    "Nimbus Niche",
    "Oracle's Oasis",
    "Phoenix Port",
    "Quartz Quay",
    "Raven's Roost",
    "Starfall Strand",
    "Tempest Terrace",
    "Utopia Upland",
    "Vesper's Vista",
    "Wildwind Wharf",
    "Expanse's Edge",
    "Yonder Yawl",
    "Zephyr's Zen",
    "Arcane Anchorage",
    "Briar's Bay",
    "Candlelight Cove",
    "Duskwave Dock",
    "Elysium Estuary",
    "Firefly Fjord",
    "Gleam's Gulf",
    "Harbinger's Hearth",
    "Iridescent Isle",
    "Journey's Jetty",
    "Kraken's Kettle",
    "Lustrous Landing",
    "Mystmere Mews",
    "Nectar's Nook",
    "Omen's Oasis",
    "Polaris Port",
    "Quest's Quay",
    "Ripple's Refuge",
    "Stardust Strand",
    "Thorn's Thoroughfare",
    "Umbrella Upland",
    "Vivid Vista",
    "Wanderer's Wharf",
    "Xerxes' Xanadu",
    "Yara's Yawl",
    "Zion's Zenith",
    "Amber's Abyss",
    "Bloom's Bay",
    "Crystal's Cradle",
    "Dawnstar Dock",
    "Echowind Estuary",
    "Flare's Fjord",
    "Glisten's Gulf",
    "Halcyon Harbor",
    "Inferno Isle",
    "Jasper's Jetty",
    "Kite's Kettle",
    "Lorelight Landing",
    "Moonmist Mews",
    "Nebula Nook",
    "Oasis's Oracle",
    "Pulse's Port",
    "Quasar's Quay",
    "Rift's Roost",
    "Sunset's Strand",
    "Torch's Thoroughfare",
]

features = {
    "Ocean": {
        "nouns": o_nouns,
        "adjectives": o_adjectives,
    },
    "Plains": {
        "nouns": p_nouns,
        "adjectives": p_adjectives,
    },
    "Hills": {
        "nouns": h_nouns,
        "adjectives": h_adjectives,
    },
    "Mountains": {
        "nouns": m_nouns,
        "adjectives": m_adjectives,
    },
    "Forest": {
        "nouns": f_nouns,
        "adjectives": f_adjectives,
    },
    "Town": {
        "name": t_name,
    }
}